name: Publish Python üêç distributions üì¶ to PyPI
on:
  release:
    types: [published]
defaults:
  run:
    shell:
      bash
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify tag matches version
        run: |
          set -ex
          version=$(grep -m 1 version pyproject.toml | grep -P '\d+\.\d+\.\d+' -o)
          tag="${GITHUB_REF/refs\/tags\/}"
          if [[ "v$version" != "$tag" ]]; then
            exit 1
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: |
          python -m pip install -U pip setuptools wheel build
      - run: |
          python -m build
      - run: |
          pip install dist/*.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build requirements
        run: |
          python -m pip install -U pip setuptools wheel build numpy cython
      - name: Setup and install manylinux1_x86_64 wheel
        run: |
          python setup.py bdist_wheel --plat-name=manylinux1_x86_64
          python -m pip install dist/*-manylinux*.whl
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python-version }}
          path: dist/*-manylinux*.whl
  publish-artifacts:
    runs-on: ubuntu-latest
    needs: [build-sdist, build-wheels]
    environment:
      name: release
      url: https://pypi.org/p/coqui-tts
    permissions:
      id-token: write
    steps:
      - run: |
          mkdir dist
      - uses: actions/download-artifact@v4
        with:
          name: "sdist"
          path: "dist/"
      - uses: actions/download-artifact@v4
        with:
          name: "wheel-3.9"
          path: "dist/"
      - uses: actions/download-artifact@v4
        with:
          name: "wheel-3.10"
          path: "dist/"
      - uses: actions/download-artifact@v4
        with:
          name: "wheel-3.11"
          path: "dist/"
      - uses: actions/download-artifact@v4
        with:
          name: "wheel-3.12"
          path: "dist/"
      - run: |
          ls -lh dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
